const midexpt2btracingQuestions = [
/*
{
  type: "tracing",
  class: "Sky Sprouts",
  subject: "Expressive Arts",
  term: "Term 3",
  part: "End Term",
  question: "Trace the following shape carefully:",
  tracingContent: "star"
},
{
  type: "tracing",
  class: "Sky Sprouts",
  subject: "Expressive Arts",
  term: "Term 3",
  part: "End Term",
  question: "Trace the following shape carefully:",
  tracingContent: "diamond",
  },
{
  type: "tracing",
  class: "Sky Sprouts",
  subject: "Expressive Arts",
  term: "Term 3",
  part: "End Term",
  question: "Trace the following shape carefully:",
  tracingContent: "pentagon"
},
{
  type: "tracing",
  class: "Sky Sprouts",
  subject: "Expressive Arts",
  term: "Term 3",
  part: "End Term",
  question: "Trace the following shape carefully:",
  tracingContent: "rectangle",
  },
{
  type: "tracing",
  class: "Sky Sprouts",
  subject: "Expressive Arts",
  term: "Term 3",
  part: "End Term",
  question: "Trace the following shape carefully:",
  tracingContent: "square"
},
{
  type: "tracing",
  class: "Sky Sprouts",
  subject: "Expressive Arts",
  term: "Term 3",
  part: "End Term",
  question: "Trace the following shape carefully:",
  tracingContent: "triangle",
  },
{
  type: "tracing",
  class: "Sky Sprouts",
  subject: "Expressive Arts",
  term: "Term 3",
  part: "End Term",
  question: "Trace the following shape carefully:",
  tracingContent: "circle"
},
{
  type: "tracing",
  class: "Sky Sprouts",
  subject: "Expressive Arts",
  term: "Term 3",
  part: "End Term",
  question: "Trace the following shape carefully:",
  tracingContent: "oval",
  },
{
  type: "tracing",
  class: "Sky Sprouts",
  subject: "Expressive Arts",
  term: "Term 3",
  part: "End Term",
  question: "Trace the following shape carefully:",
  tracingContent: "crescent"
},
{
  type: "tracing",
  class: "Sky Sprouts",
  subject: "Expressive Arts",
  term: "Term 3",
  part: "End Term",
  question: "Trace the following shape carefully:",
  tracingContent: "hexagon",
  },
{
  type: "tracing",
  class: "Sky Sprouts",
  subject: "Expressive Arts",
  term: "Term 3",
  part: "End Term",
  question: "Trace the following shape carefully:",
  tracingContent: "heptagon",
  },
{
  type: "tracing",
  class: "Sky Sprouts",
  subject: "Expressive Arts",
  term: "Term 3",
  part: "End Term",
  question: "Trace the following shape carefully:",
  tracingContent: "octagon",
  },
{
  type: "tracing",
  class: "Sky Sprouts",
  subject: "Expressive Arts",
  term: "Term 3",
  part: "End Term",
  question: "Trace the following shape carefully:",
  tracingContent: "decagon",
  },
{
  type: "tracing",
  class: "Sky Sprouts",
  subject: "Expressive Arts",
  term: "Term 3",
  part: "End Term",
  question: "Trace the following shape carefully:",
  tracingContent: "heart",
  },
{
  type: "tracing",
  class: "Sky Sprouts",
  subject: "Expressive Arts",
  term: "Term 3",
  part: "End Term",
  question: "Trace the following shape carefully:",
  tracingContent: "nonagon",
  }*/
];