const g3matht3bnumberLineQuestions = [
{
    type: "numberLine",
    class: "Wing Whiz",
    subject: "Mathematics",
    term: "Term 3",
    part: "End Term",
    question: "Find the sum on the number line",
    startRange: -1,
    endRange: 13,
    mathExpression: "7 + 5",
},
{
    type: "numberLine",
    class: "Wing Whiz",
    subject: "Mathematics",
    term: "Term 3",
    part: "End Term",
    question: "Find the sum on the number line",
    startRange: -8,
    endRange: 1,
    mathExpression: "-7 + 5",
},
{
    type: "numberLine",
    class: "Wing Whiz",
    subject: "Mathematics",
    term: "Term 3",
    part: "End Term",
    question: "Find the difference on the number line",
    startRange: -5,
    endRange: 5,
    mathExpression: "3 - 5",
},
{
    type: "numberLine",
    class: "Wing Whiz",
    subject: "Mathematics",
    term: "Term 3",
    part: "End Term",
    question: "Show this expression on the number line.",
    startRange: -3,
    endRange: 4,
    mathExpression: "x < 2",
},
{
    type: "numberLine",
    class: "Wing Whiz",
    subject: "Mathematics",
    term: "Term 3",
    part: "End Term",
    question: "Show this expression on the number line.",
    startRange: -5,
    endRange: 0,
    mathExpression: "x > -4",
},
{
    type: "numberLine",
    class: "Wing Whiz",
    subject: "Mathematics",
    term: "Term 3",
    part: "End Term",
    question: "Show this expression on the number line.",
    startRange: -3,
    endRange: 4,
    mathExpression: "x <= 0",
},
{
    type: "numberLine",
    class: "Wing Whiz",
    subject: "Mathematics",
    term: "Term 3",
    part: "End Term",
    question: "Show this expression on the number line.",
    startRange: -3,
    endRange: 4,
    mathExpression: "x >= -2",
}
];