const recsp2t1bimageBasedQuestions = [
    {
        type: "maze",
        class: "Nestlings Navigators",
        subject: "Special Paper 2",
        term: "Term 1",
        part: "End Term",
        puzzleSrc: "images/maze/reception/maze2a.jpg",
        question: "Answer the maze puzzle given below by finding your way from the 'Start' to the 'Finish' without crossing any walls.",
        description: "Nestling Maze"
    },
    {
        type: "maze",
        class: "Nestlings Navigators",
        subject: "Special Paper 2",
        term: "Term 1",
        part: "End Term",
        puzzleSrc: "images/maze/reception/maze2b.jpg",
        question: "Answer the maze puzzle given below by finding your way from the 'Start' to the 'Finish' without crossing any walls.",
    },
    {
        type: "maze",
        class: "Nestlings Navigators",
        subject: "Special Paper 2",
        term: "Term 1",
        part: "End Term",
        puzzleSrc: "images/maze/reception/maze2c.jpg",
        question: "Answer the maze puzzle given below by finding your way from the 'Start' to the 'Finish' without crossing any walls.",
    },
    {
        type: "maze",
        class: "Nestlings Navigators",
        subject: "Special Paper 2",
        term: "Term 1",
        part: "End Term",
        puzzleSrc: "images/maze/reception/maze2d.jpg",
        question: "Answer the maze puzzle given below by finding your way from the 'Start' to the 'Finish' without crossing any walls.",
    },
    {
        type: "maze",
        class: "Nestlings Navigators",
        subject: "Special Paper 2",
        term: "Term 1",
        part: "End Term",
        puzzleSrc: "images/maze/reception/maze2e.jpg",
        question: "Answer the maze puzzle given below by finding your way from the 'Start' to the 'Finish' without crossing any walls.",
    },
    {
        type: "maze",
        class: "Nestlings Navigators",
        subject: "Special Paper 2",
        term: "Term 1",
        part: "End Term",
        puzzleSrc: "images/maze/reception/maze2f.jpg",
        question: "Answer the maze puzzle given below by finding your way from the 'Start' to the 'Finish' without crossing any walls.",
    },
    {
        type: "maze",
        class: "Nestlings Navigators",
        subject: "Special Paper 2",
        term: "Term 1",
        part: "End Term",
        puzzleSrc: "images/maze/reception/maze2g.jpg",
        question: "Answer the maze puzzle given below by finding your way from the 'Start' to the 'Finish' without crossing any walls.",
    },
    {
        type: "maze",
        class: "Nestlings Navigators",
        subject: "Special Paper 2",
        term: "Term 1",
        part: "End Term",
        puzzleSrc: "images/maze/reception/maze2h.jpg",
        question: "Answer the maze puzzle given below by finding your way from the 'Start' to the 'Finish' without crossing any walls.",
    },
    {
        type: "maze",
        class: "Nestlings Navigators",
        subject: "Special Paper 2",
        term: "Term 1",
        part: "End Term",
        puzzleSrc: "images/maze/reception/maze2i.jpg",
        question: "Answer the maze puzzle given below by finding your way from the 'Start' to the 'Finish' without crossing any walls.",
    },
    {
        type: "maze",
        class: "Nestlings Navigators",
        subject: "Special Paper 2",
        term: "Term 1",
        part: "End Term",
        puzzleSrc: "images/maze/reception/maze2j.jpg",
        question: "Answer the maze puzzle given below by finding your way from the 'Start' to the 'Finish' without crossing any walls.",
    }
];