const g3scit2bmultipleChoiceQuestions = [

  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "What is light?",
    "choices": ["Energy produced by sound", "Visible electromagnetic radiation", "Heat generated by fire", "Liquid substance in lamps"],
    "answer": "Visible electromagnetic radiation"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "Why is light important in our daily lives?",
    "choices": ["It helps plants grow", "It creates shadows", "It generates electricity", "It produces heat"],
    "answer": "It helps plants grow"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "Which of these is a natural source of light?",
    "choices": ["Light bulb", "Firefly", "Lamp", "Flashlight"],
    "answer": "Firefly"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "Name an artificial source of light commonly used indoors.",
    "choices": ["Moonlight", "Candle", "Starlight", "Sunlight"],
    "answer": "Candle"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "How does sunlight benefit plants?",
    "choices": ["Provides water", "Helps in photosynthesis", "Prevents growth", "Produces oxygen"],
    "answer": "Helps in photosynthesis"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "Which artificial light source uses electricity to produce light?",
    "choices": ["Candle", "Lantern", "Flashlight", "Campfire"],
    "answer": "Flashlight"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "What role does light play in vision?",
    "choices": ["Creates warmth", "Causes darkness", "Enables us to see objects", "Enhances sound"],
    "answer": "Enables us to see objects"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "How does light travel from the sun to Earth?",
    "choices": ["Through water", "As sound waves", "Through vacuum", "In straight lines"],
    "answer": "In straight lines"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "Which natural phenomenon is caused by the reflection of light in droplets of water?",
    "choices": ["Lightning", "Thunder", "Rainbow", "Blizzard"],
    "answer": "Rainbow"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "What do we call the process of light bouncing off a surface?",
    "choices": ["Absorption", "Refraction", "Reflection", "Diffraction"],
    "answer": "Reflection"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "How does a flashlight produce light?",
    "choices": ["By burning fuel", "By absorbing light", "By emitting light from a bulb", "By storing electricity"],
    "answer": "By emitting light from a bulb"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "Which type of light source is used to mimic natural sunlight indoors?",
    "choices": ["Incandescent bulb", "LED light", "Fluorescent tube", "Halogen lamp"],
    "answer": "Halogen lamp"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "What happens when light passes through a prism?",
    "choices": ["It turns into heat", "It changes direction", "It splits into colors", "It absorbs colors"],
    "answer": "It splits into colors"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "How does light enable communication using optical fibers?",
    "choices": ["By transmitting signals", "By reflecting sound", "By storing data", "By creating shadows"],
    "answer": "By transmitting signals"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "Which natural source of light is essential for the growth of plants?",
    "choices": ["Starlight", "Moonlight", "Sunlight", "Torchlight"],
    "answer": "Sunlight"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "Why do we see shadows when light is blocked by an object?",
    "choices": ["Light is absorbed", "Light is reflected", "Light is refracted", "Light is obstructed"],
    "answer": "Light is obstructed"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "How does light help us determine the color of objects?",
    "choices": ["By absorbing colors", "By emitting colors", "By reflecting colors", "By storing colors"],
    "answer": "By reflecting colors"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "Which artificial light source is commonly used for street lighting?",
    "choices": ["Lantern", "Torch", "Sodium vapor lamp", "Oil lamp"],
    "answer": "Sodium vapor lamp"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "In what ways does light influence our sense of sight?",
    "choices": ["By creating warmth", "By causing blindness", "By allowing us to see colors", "By enhancing hearing"],
    "answer": "By allowing us to see colors"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "What is the importance of understanding the properties of light in everyday life?",
    "choices": ["Helps in cooking", "Aids in navigation", "Supports sleep", "Maintains temperature"],
    "answer": "Aids in navigation"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "What happens when light bounces off a smooth surface like a mirror?",
    "choices": ["Absorption", "Refraction", "Reflection", "Diffraction"],
    "answer": "Reflection"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "Which phenomenon causes a pencil placed in a glass of water to appear bent?",
    "choices": ["Absorption", "Reflection", "Refraction", "Dispersion"],
    "answer": "Refraction"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "How does a prism separate white light into different colors?",
    "choices": ["Reflection", "Refraction", "Diffraction", "Absorption"],
    "answer": "Refraction"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "What is the bending of light as it passes from one medium to another called?",
    "choices": ["Absorption", "Reflection", "Refraction", "Diffraction"],
    "answer": "Refraction"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "Which property of light explains why a rainbow forms after rain?",
    "choices": ["Reflection", "Refraction", "Diffraction", "Dispersion"],
    "answer": "Dispersion"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "How does light behave when passing through a magnifying glass?",
    "choices": ["Absorption", "Reflection", "Refraction", "Diffraction"],
    "answer": "Refraction"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "Which property of light causes a spoon in a glass of water to look distorted?",
    "choices": ["Reflection", "Refraction", "Dispersion", "Absorption"],
    "answer": "Refraction"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "What happens when light passes through a narrow slit or opening?",
    "choices": ["Absorption", "Reflection", "Refraction", "Diffraction"],
    "answer": "Diffraction"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "How can you demonstrate the reflection of light using a mirror?",
    "choices": ["By bending light", "By blocking light", "By bouncing light", "By absorbing light"],
    "answer": "By bouncing light"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "Which experiment can demonstrate the refraction of light?",
    "choices": ["Passing light through a prism", "Blocking light with a wall", "Heating light with a lamp", "Mixing light with colors"],
    "answer": "Passing light through a prism"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "What tool is used to observe the dispersion of light into a spectrum of colors?",
    "choices": ["Microscope", "Telescope", "Prism", "Compass"],
    "answer": "Prism"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "How does light behave when passing through a transparent object?",
    "choices": ["It absorbs colors", "It reflects off", "It bends", "It creates shadows"],
    "answer": "It bends"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "Why does a rainbow appear in the sky after rain?",
    "choices": ["Due to reflection", "Due to absorption", "Due to refraction", "Due to diffraction"],
    "answer": "Due to refraction"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "What happens when light strikes a rough surface like a piece of paper?",
    "choices": ["It absorbs colors", "It reflects in different directions", "It refracts into a spectrum", "It bends around objects"],
    "answer": "It reflects in different directions"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "Which property of light explains why a glass of water looks empty when viewed from the side?",
    "choices": ["Reflection", "Refraction", "Diffraction", "Dispersion"],
    "answer": "Refraction"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "How does light interact with a convex lens?",
    "choices": ["It absorbs light", "It reflects light", "It refracts light", "It diffracts light"],
    "answer": "It refracts light"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "What happens when light passes through a glass prism?",
    "choices": ["It absorbs colors", "It reflects off", "It refracts and disperses into colors", "It diffracts and spreads out"],
    "answer": "It refracts and disperses into colors"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "Why does a straw appear broken when placed in a glass of water?",
    "choices": ["Due to reflection", "Due to absorption", "Due to refraction", "Due to diffraction"],
    "answer": "Due to refraction"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "How does light behave when passing through a concave lens?",
    "choices": ["It reflects light", "It absorbs light", "It refracts light", "It diffracts light"],
    "answer": "It refracts light"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "Which experiment can demonstrate the dispersion of light into different colors?",
    "choices": ["Using a magnifying glass", "Using a mirror", "Using a prism", "Using a flashlight"],
    "answer": "Using a prism"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "How are shadows formed?",
    "choices": ["When objects emit light", "When objects absorb light", "When objects block light", "When objects reflect light"],
    "answer": "When objects block light"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "What causes the size of a shadow to change?",
    "choices": ["Changing the shape of the object", "Moving the light source closer", "Using a different material for the object", "Adjusting the color of the object"],
    "answer": "Moving the light source closer"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "Where is the shadow cast when the light source is directly above the object?",
    "choices": ["Behind the object", "In front of the object", "Under the object", "Beside the object"],
    "answer": "Under the object"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "How does the position of the light source affect the shape of a shadow?",
    "choices": ["It changes the color of the shadow", "It alters the size of the shadow", "It removes the shadow", "It creates multiple shadows"],
    "answer": "It alters the size of the shadow"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "Why does a shadow appear shorter during noon compared to sunrise or sunset?",
    "choices": ["Due to the angle of the sunlight", "Due to the size of the object", "Due to the shape of the shadow", "Due to the color of the object"],
    "answer": "Due to the angle of the sunlight"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "What happens to a shadow when the object moves closer to the light source?",
    "choices": ["It becomes longer", "It becomes shorter", "It disappears", "It changes color"],
    "answer": "It becomes shorter"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "Which type of light source can create multiple shadows?",
    "choices": ["Flashlight", "Candle", "Lamp", "Sunlight"],
    "answer": "Sunlight"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "How does the size of a shadow change with the distance of the light source?",
    "choices": ["It stays the same", "It gets smaller", "It gets larger", "It becomes darker"],
    "answer": "It gets larger"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "What happens if the object is transparent and light passes through it?",
    "choices": ["It creates a darker shadow", "It produces no shadow", "It forms a colored shadow", "It reflects the shadow"],
    "answer": "It produces no shadow"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "Why does the shape of a shadow change as the light source moves?",
    "choices": ["Due to the angle of the object", "Due to the shape of the light source", "Due to the position of the object", "Due to the brightness of the shadow"],
    "answer": "Due to the angle of the object"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "What can you learn about an object by examining its shadow?",
    "choices": ["Its weight", "Its color", "Its shape", "Its texture"],
    "answer": "Its shape"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "How does the position of the light source affect the direction of a shadow?",
    "choices": ["It changes the shape of the shadow", "It moves the shadow closer", "It shifts the shadow angle", "It alters the shadow color"],
    "answer": "It changes the shape of the shadow"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "What happens to a shadow when the light source is blocked by another object?",
    "choices": ["It becomes fainter", "It moves faster", "It changes direction", "It disappears temporarily"],
    "answer": "It disappears temporarily"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "How does the distance between the object and the surface affect the shadow?",
    "choices": ["It makes the shadow darker", "It makes the shadow smaller", "It makes the shadow longer", "It makes the shadow lighter"],
    "answer": "It makes the shadow larger"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "Which factor affects the sharpness of a shadow's edge?",
    "choices": ["The size of the object", "The shape of the light source", "The color of the object", "The intensity of the light source"],
    "answer": "The size of the object"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "Why does a shadow appear distorted when the object is placed on a curved surface?",
    "choices": ["Due to the angle of the light source", "Due to the shape of the object", "Due to the position of the object", "Due to the curvature of the surface"],
    "answer": "Due to the curvature of the surface"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "How does the angle of the light source affect the length of a shadow?",
    "choices": ["It makes the shadow darker", "It makes the shadow shorter", "It makes the shadow longer", "It makes the shadow wider"],
    "answer": "It makes the shadow longer"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "What happens to a shadow when the object is rotated?",
    "choices": ["It becomes larger", "It changes shape", "It disappears", "It becomes transparent"],
    "answer": "It changes shape"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "Which condition would create the darkest shadow?",
    "choices": ["Using a translucent object", "Using a reflective surface", "Using a transparent material", "Using a solid, opaque object"],
    "answer": "Using a solid, opaque object"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "How does the position of the observer affect the appearance of a shadow?",
    "choices": ["It changes the shape of the shadow", "It alters the color of the shadow", "It shifts the location of the shadow", "It enhances the intensity of the shadow"],
    "answer": "It changes the shape of the shadow"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "How does the angle of the light source affect the length of a shadow?",
    "choices": ["It shortens the shadow", "It lengthens the shadow", "It darkens the shadow", "It changes the color of the shadow"],
    "answer": "It lengthens the shadow"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "At what time of day are shadows typically longest?",
    "choices": ["Noon", "Sunrise", "Sunset", "Midnight"],
    "answer": "Sunrise"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "What causes shadows to change direction throughout the day?",
    "choices": ["Movement of clouds", "Rotation of the Earth", "Changing seasons", "Magnetic fields"],
    "answer": "Rotation of the Earth"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "How does the position of the sun affect the direction of a shadow?",
    "choices": ["It makes the shadow darker", "It shifts the shadow angle", "It creates multiple shadows", "It absorbs the shadow"],
    "answer": "It shifts the shadow angle"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "What happens to shadow lengths as the sun rises higher in the sky?",
    "choices": ["They stay the same", "They become shorter", "They become longer", "They disappear"],
    "answer": "They become shorter"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "Why do shadows appear shortest at noon compared to other times of the day?",
    "choices": ["Due to the brightness of the sun", "Due to the position of the observer", "Due to the angle of the light", "Due to the shape of the object"],
    "answer": "Due to the angle of the light"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "How does the angle of the light affect the shape of a shadow?",
    "choices": ["It changes the color of the shadow", "It alters the size of the shadow", "It adjusts the position of the shadow", "It modifies the shape of the shadow edge"],
    "answer": "It modifies the shape of the shadow edge"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "What causes shadows to appear longer or shorter during different seasons?",
    "choices": ["Changes in daylight hours", "Movement of the moon", "Rotation of the Earth", "Magnetic pole shifts"],
    "answer": "Changes in daylight hours"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "Which factor contributes to the length of a shadow at sunrise or sunset?",
    "choices": ["The color of the sky", "The intensity of the light", "The angle of the sun", "The temperature of the air"],
    "answer": "The angle of the sun"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "How does the Earth's tilt affect the length of shadows during different times of the year?",
    "choices": ["It increases the shadow length", "It decreases the shadow length", "It changes the shadow direction", "It eliminates shadows"],
    "answer": "It increases the shadow length"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "What happens to the shape of a shadow as the light source moves closer to the object?",
    "choices": ["It becomes more defined", "It becomes fuzzy", "It becomes transparent", "It becomes smaller"],
    "answer": "It becomes more defined"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "Why do shadows appear to move throughout the day?",
    "choices": ["Due to changes in wind direction", "Due to Earth's rotation", "Due to cloud cover", "Due to seasonal changes"],
    "answer": "Due to Earth's rotation"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "How does the position of the observer affect the length of a shadow?",
    "choices": ["It changes the color of the shadow", "It alters the direction of the shadow", "It adjusts the shape of the shadow", "It affects the angle of the shadow"],
    "answer": "It alters the direction of the shadow"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "Which factor determines the length of a shadow cast by an object?",
    "choices": ["The weight of the object", "The density of the object", "The size of the object", "The shape of the object"],
    "answer": "The size of the object"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "What causes shadows to appear fainter during cloudy days?",
    "choices": ["Diffraction of light", "Absorption of light", "Reflection of light", "Refraction of light"],
    "answer": "Diffraction of light"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "How does the direction of a shadow change from morning to evening?",
    "choices": ["It remains constant", "It shifts east to west", "It moves north to south", "It rotates clockwise"],
    "answer": "It shifts east to west"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "What happens to shadow lengths as the sun sets in the evening?",
    "choices": ["They become longer", "They become shorter", "They disappear", "They remain the same"],
    "answer": "They become longer"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "Why do shadows appear sharper when the sun is directly overhead?",
    "choices": ["Due to diffraction of light", "Due to refraction of light", "Due to absorption of light", "Due to direct sunlight"],
    "answer": "Due to direct sunlight"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "How does the angle of the sun affect the clarity of a shadow's edges?",
    "choices": ["It blurs the shadow edges", "It sharpens the shadow edges", "It changes the shadow color", "It shortens the shadow length"],
    "answer": "It sharpens the shadow edges"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "What causes the length of a shadow to vary throughout the day?",
    "choices": ["Movement of the moon", "Changes in air temperature", "Rotation of the Earth", "Magnetic field fluctuations"],
    "answer": "Rotation of the Earth"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "Which term describes a material that allows light to pass through completely?",
    "choices": ["Opaque", "Translucent", "Transparent", "Reflective"],
    "answer": "Transparent"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "What type of material allows some light to pass through but scatters it in different directions?",
    "choices": ["Opaque", "Reflective", "Translucent", "Transparent"],
    "answer": "Translucent"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "Which property describes a material that does not allow light to pass through at all?",
    "choices": ["Transparent", "Translucent", "Opaque", "Reflective"],
    "answer": "Opaque"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "What happens to light when it passes through a transparent material?",
    "choices": ["It reflects off the surface", "It is absorbed by the material", "It passes through without scattering", "It changes color"],
    "answer": "It passes through without scattering"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "Which material allows you to see shapes and colors clearly through it?",
    "choices": ["Opaque", "Reflective", "Transparent", "Translucent"],
    "answer": "Transparent"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "How does a translucent material differ from a transparent one?",
    "choices": ["It allows less light to pass through", "It allows more light to pass through", "It reflects light back", "It absorbs light"],
    "answer": "It allows less light to pass through"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "Which type of material is useful for creating privacy while still allowing some light to pass through?",
    "choices": ["Transparent", "Reflective", "Opaque", "Translucent"],
    "answer": "Translucent"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "What property makes a material suitable for use in windows for clear visibility?",
    "choices": ["Opaque", "Reflective", "Transparent", "Translucent"],
    "answer": "Transparent"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "Which material type allows some light to pass through but blurs the objects seen through it?",
    "choices": ["Transparent", "Reflective", "Opaque", "Translucent"],
    "answer": "Translucent"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "Why is glass considered a transparent material?",
    "choices": ["It reflects light", "It absorbs light", "It allows light to pass through", "It blocks light completely"],
    "answer": "It allows light to pass through"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "Which property of a material determines how much light it allows to pass through?",
    "choices": ["Density", "Color", "Opacity", "Transparency"],
    "answer": "Transparency"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "How does an opaque material differ from a transparent one in terms of light passage?",
    "choices": ["It allows less light to pass through", "It allows more light to pass through", "It reflects light", "It scatters light"],
    "answer": "It allows less light to pass through"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "What type of material prevents you from seeing through it and blocks light completely?",
    "choices": ["Translucent", "Transparent", "Opaque", "Reflective"],
    "answer": "Opaque"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "Which material allows you to see shapes and colors vaguely through it?",
    "choices": ["Opaque", "Translucent", "Transparent", "Reflective"],
    "answer": "Translucent"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "How does the thickness of a transparent material affect the passage of light?",
    "choices": ["It increases transparency", "It decreases transparency", "It changes color", "It reflects light"],
    "answer": "It decreases transparency"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "What makes frosted glass different from regular transparent glass?",
    "choices": ["It allows more light through", "It scatters light", "It reflects light", "It absorbs light"],
    "answer": "It scatters light"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "Which material type allows light to pass through but does not allow you to see objects clearly on the other side?",
    "choices": ["Opaque", "Reflective", "Translucent", "Transparent"],
    "answer": "Translucent"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "What property of a material allows it to block light effectively?",
    "choices": ["Transparency", "Reflectivity", "Opacity", "Translucency"],
    "answer": "Opacity"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "Why is paper considered translucent rather than transparent?",
    "choices": ["It allows some light through", "It reflects light", "It blocks light completely", "It scatters light"],
    "answer": "It allows some light through"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "Which material type allows light to pass through without changing its direction?",
    "choices": ["Reflective", "Translucent", "Transparent", "Opaque"],
    "answer": "Transparent"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "What causes white light to separate into different colors when passing through a prism?",
    "choices": ["Reflection", "Absorption", "Refraction", "Diffraction"],
    "answer": "Refraction"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "How does a prism separate light into a spectrum of colors?",
    "choices": ["By reflecting light", "By absorbing light", "By refracting light at different angles", "By diffracting light waves"],
    "answer": "By refracting light at different angles"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "What is the order of colors in a rainbow from top to bottom?",
    "choices": ["Red, Orange, Yellow, Green, Blue, Indigo, Violet", "Violet, Blue, Green, Yellow, Orange, Red", "Red, Yellow, Blue, Green, Orange, Indigo, Violet", "Blue, Green, Red, Yellow, Orange, Violet, Indigo"],
    "answer": "Red, Orange, Yellow, Green, Blue, Indigo, Violet"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "How does light create a rainbow after rain?",
    "choices": ["By absorption", "By reflection", "By refraction and dispersion", "By diffraction and absorption"],
    "answer": "By refraction and dispersion"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "Which phenomenon causes the formation of a secondary rainbow with reversed colors?",
    "choices": ["Refraction", "Reflection", "Interference", "Dispersion"],
    "answer": "Dispersion"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "What happens when white light passes through a water droplet to create a rainbow?",
    "choices": ["The light is absorbed", "The light is reflected", "The light is refracted and dispersed", "The light is diffracted and absorbed"],
    "answer": "The light is refracted and dispersed"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "How does the angle of sunlight affect the visibility of a rainbow?",
    "choices": ["It makes the rainbow fainter", "It changes the rainbow's colors", "It alters the rainbow's position", "It brightens the rainbow"],
    "answer": "It alters the rainbow's position"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "Which color of light bends the most when passing through a prism?",
    "choices": ["Red", "Green", "Blue", "Violet"],
    "answer": "Violet"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "What causes the colors of a rainbow to spread out in the sky?",
    "choices": ["Reflection", "Absorption", "Refraction at different angles", "Diffraction through clouds"],
    "answer": "Refraction at different angles"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "How can you demonstrate the separation of light into colors using a prism?",
    "choices": ["By blocking light with a prism", "By reflecting light with a prism", "By passing light through a prism", "By absorbing light with a prism"],
    "answer": "By passing light through a prism"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "What happens when two primary colors of light overlap?",
    "choices": ["They create a secondary color", "They absorb each other", "They reflect off each other", "They cancel each other out"],
    "answer": "They create a secondary color"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "Which colors combine to create white light when mixed together?",
    "choices": ["Red and Blue", "Green and Blue", "Red, Green, and Blue", "Yellow and Cyan"],
    "answer": "Red, Green, and Blue"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "How does mixing different colors of light affect the resulting color?",
    "choices": ["It darkens the color", "It brightens the color", "It changes the color", "It absorbs the color"],
    "answer": "It changes the color"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "What happens when you mix red and green light together?",
    "choices": ["They create yellow light", "They create magenta light", "They create cyan light", "They create white light"],
    "answer": "They create yellow light"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "Which color is created by mixing red and blue light together?",
    "choices": ["Yellow", "Green", "Cyan", "Magenta"],
    "answer": "Magenta"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "What is the result of mixing all primary colors of light together?",
    "choices": ["Black light", "White light", "Gray light", "Rainbow light"],
    "answer": "White light"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "How does the process of color mixing with light differ from mixing pigments?",
    "choices": ["Light mixing results in primary colors", "Pigment mixing results in subtractive colors", "Light mixing absorbs colors", "Pigment mixing reflects colors"],
    "answer": "Pigment mixing results in subtractive colors"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "Why does a color wheel help understand primary and secondary colors?",
    "choices": ["It shows how colors reflect light", "It demonstrates how colors mix together", "It absorbs different colors", "It refracts light at angles"],
    "answer": "It demonstrates how colors mix together"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "What happens when yellow light shines on a blue object?",
    "choices": ["The object turns green", "The object turns red", "The object appears yellow", "The object appears black"],
    "answer": "The object appears black"
  },
  {
    "type": "multiple_choice",
    "class": "Wing Whiz",
    "subject": "Science",
    "term": "Term 2",
    "part": "End Term",
    "question": "How does the color of an object change under different colored lights?",
    "choices": ["It absorbs light", "It reflects light", "It diffracts light", "It scatters light"],
    "answer": "It reflects light"
  }


];