const recmatht3bobjectMathQuestions = [
{
    type: "objectMath",
    class: "Nestlings Navigators",
    subject: "Mental Math",
    term: "Term 3",
    part: "End Term",
    question: "Solve the problem by counting the objects.",
    objectMathPrompt: "Object Math",
    num1: 9,
    num2: 6,
    operator: "+",
    objectImage: "images/science/middle/well.png" // Replace with actual image path or URL
},
{
    type: "objectMath",
    class: "Nestlings Navigators",
    subject: "Mental Math",
    term: "Term 3",
    part: "End Term",
    question: "Solve the problem by counting the objects.",
    objectMathPrompt: "Object Math",
    num1: 3,
    num2: 5,
    operator: "+",
    objectImage: "images/science/middle/apple.png" // Replace with actual image path or URL
},
{
    type: "objectMath",
    class: "Nestlings Navigators",
    subject: "Mental Math",
    term: "Term 3",
    part: "End Term",
    question: "Solve the problem by counting the objects.",
    objectMathPrompt: "Object Math",
    num1: 10,
    num2: 7,
    operator: "+",
    objectImage: "images/science/middle/cat.png" // Replace with actual image path or URL
},
{
    type: "objectMath",
    class: "Nestlings Navigators",
    subject: "Mental Math",
    term: "Term 3",
    part: "End Term",
    question: "Solve the problem by counting the objects.",
    objectMathPrompt: "Object Math",
    num1: 12,
    num2: 5,
    operator: "+",
    objectImage: "images/science/middle/cow.png" // Replace with actual image path or URL
},
{
    type: "objectMath",
    class: "Nestlings Navigators",
    subject: "Mental Math",
    term: "Term 3",
    part: "End Term",
    question: "Solve the problem by counting the objects.",
    objectMathPrompt: "Object Math",
    num1: 18,
    num2: 7,
    operator: "+",
    objectImage: "images/science/middle/owl.png" // Replace with actual image path or URL
},
{
    type: "objectMath",
    class: "Nestlings Navigators",
    subject: "Mental Math",
    term: "Term 3",
    part: "End Term",
    question: "Solve the problem by counting the objects.",
    objectMathPrompt: "Object Math",
    num1: 6,
    num2: 14,
    operator: "+",
    objectImage: "images/science/middle/shark.png" // Replace with actual image path or URL
},
{
    type: "objectMath",
    class: "Nestlings Navigators",
    subject: "Mental Math",
    term: "Term 3",
    part: "End Term",
    question: "Solve the problem by counting the objects.",
    objectMathPrompt: "Object Math",
    num1: 3,
    num2: 15,
    operator: "+",
    objectImage: "images/science/middle/squirrel.png" // Replace with actual image path or URL
},
{
    type: "objectMath",
    class: "Nestlings Navigators",
    subject: "Mental Math",
    term: "Term 3",
    part: "End Term",
    question: "Solve the problem by counting the objects.",
    objectMathPrompt: "Object Math",
    num1: 19,
    num2: 16,
    operator: "+",
    objectImage: "images/science/middle/jellyfish.png" // Replace with actual image path or URL
}
];