const recmatht3btimeQuestions = [
{
    type: "time",
    class: "Nestlings Navigators",
    subject: "Mathematics",
    term: "Term 3",
    part: "End Term",
    question: "What time is shown on the clock?",
    timeMode: "read",
    displayedHour: 1,
    displayedMinute: 00,
    correctAnswer: "1:00"
},
{
    type: "time",
    class: "Nestlings Navigators",
    subject: "Mathematics",
    term: "Term 3",
    part: "End Term",
    question: "What time is shown on the clock?",
    timeMode: "read",
    displayedHour: 1,
    displayedMinute: 15,
    correctAnswer: "1:15"
},
{
    type: "time",
    class: "Nestlings Navigators",
    subject: "Mathematics",
    term: "Term 3",
    part: "End Term",
    question: "What time is shown on the clock?",
    timeMode: "read",
    displayedHour: 1,
    displayedMinute: 30,
    correctAnswer: "1:30"
},
{
    type: "time",
    class: "Nestlings Navigators",
    subject: "Mathematics",
    term: "Term 3",
    part: "End Term",
    question: "What time is shown on the clock?",
    timeMode: "read",
    displayedHour: 1,
    displayedMinute: 45,
    correctAnswer: "1:45"
},
{
    type: "time",
    class: "Nestlings Navigators",
    subject: "Mathematics",
    term: "Term 3",
    part: "End Term",
    question: "What time is shown on the clock?",
    timeMode: "read",
    displayedHour: 2,
    displayedMinute: 00,
    correctAnswer: "2:00"
},
{
    type: "time",
    class: "Nestlings Navigators",
    subject: "Mathematics",
    term: "Term 3",
    part: "End Term",
    question: "What time is shown on the clock?",
    timeMode: "read",
    displayedHour: 2,
    displayedMinute: 15,
    correctAnswer: "2:15"
},
{
    type: "time",
    class: "Nestlings Navigators",
    subject: "Mathematics",
    term: "Term 3",
    part: "End Term",
    question: "What time is shown on the clock?",
    timeMode: "read",
    displayedHour: 2,
    displayedMinute: 30,
    correctAnswer: "2:30"
},
{
    type: "time",
    class: "Nestlings Navigators",
    subject: "Mathematics",
    term: "Term 3",
    part: "End Term",
    question: "What time is shown on the clock?",
    timeMode: "read",
    displayedHour: 2,
    displayedMinute: 45,
    correctAnswer: "2:45"
},
{
    type: "time",
    class: "Nestlings Navigators",
    subject: "Mathematics",
    term: "Term 3",
    part: "End Term",
    question: "What time is shown on the clock?",
    timeMode: "read",
    displayedHour: 3,
    displayedMinute: 00,
    correctAnswer: "3:00"
},
{
    type: "time",
    class: "Nestlings Navigators",
    subject: "Mathematics",
    term: "Term 3",
    part: "End Term",
    question: "What time is shown on the clock?",
    timeMode: "read",
    displayedHour: 3,
    displayedMinute: 15,
    correctAnswer: "3:15"
},
{
    type: "time",
    class: "Nestlings Navigators",
    subject: "Mathematics",
    term: "Term 3",
    part: "End Term",
    question: "What time is shown on the clock?",
    timeMode: "read",
    displayedHour: 3,
    displayedMinute: 30,
    correctAnswer: "3:30"
},
{
    type: "time",
    class: "Nestlings Navigators",
    subject: "Mathematics",
    term: "Term 3",
    part: "End Term",
    question: "What time is shown on the clock?",
    timeMode: "read",
    displayedHour: 3,
    displayedMinute: 45,
    correctAnswer: "3:45"
},
{
    type: "time",
    class: "Nestlings Navigators",
    subject: "Mathematics",
    term: "Term 3",
    part: "End Term",
    question: "What time is shown on the clock?",
    timeMode: "read",
    displayedHour: 4,
    displayedMinute: 00,
    correctAnswer: "4:00"
},
{
    type: "time",
    class: "Nestlings Navigators",
    subject: "Mathematics",
    term: "Term 3",
    part: "End Term",
    question: "What time is shown on the clock?",
    timeMode: "read",
    displayedHour: 4,
    displayedMinute: 15,
    correctAnswer: "4:15"
},
{
    type: "time",
    class: "Nestlings Navigators",
    subject: "Mathematics",
    term: "Term 3",
    part: "End Term",
    question: "What time is shown on the clock?",
    timeMode: "read",
    displayedHour: 4,
    displayedMinute: 30,
    correctAnswer: "4:30"
},
{
    type: "time",
    class: "Nestlings Navigators",
    subject: "Mathematics",
    term: "Term 3",
    part: "End Term",
    question: "What time is shown on the clock?",
    timeMode: "read",
    displayedHour: 4,
    displayedMinute: 45,
    correctAnswer: "4:45"
},
{
    type: "time",
    class: "Nestlings Navigators",
    subject: "Mathematics",
    term: "Term 3",
    part: "End Term",
    question: "What time is shown on the clock?",
    timeMode: "read",
    displayedHour: 5,
    displayedMinute: 00,
    correctAnswer: "5:00"
},
{
    type: "time",
    class: "Nestlings Navigators",
    subject: "Mathematics",
    term: "Term 3",
    part: "End Term",
    question: "What time is shown on the clock?",
    timeMode: "read",
    displayedHour: 5,
    displayedMinute: 15,
    correctAnswer: "5:15"
},
{
    type: "time",
    class: "Nestlings Navigators",
    subject: "Mathematics",
    term: "Term 3",
    part: "End Term",
    question: "What time is shown on the clock?",
    timeMode: "read",
    displayedHour: 5,
    displayedMinute: 30,
    correctAnswer: "5:30"
},
{
    type: "time",
    class: "Nestlings Navigators",
    subject: "Mathematics",
    term: "Term 3",
    part: "End Term",
    question: "What time is shown on the clock?",
    timeMode: "read",
    displayedHour: 5,
    displayedMinute: 45,
    correctAnswer: "5:45"
},
{
    type: "time",
    class: "Nestlings Navigators",
    subject: "Mathematics",
    term: "Term 3",
    part: "End Term",
    question: "What time is shown on the clock?",
    timeMode: "read",
    displayedHour: 6,
    displayedMinute: 00,
    correctAnswer: "6:00"
},
{
    type: "time",
    class: "Nestlings Navigators",
    subject: "Mathematics",
    term: "Term 3",
    part: "End Term",
    question: "What time is shown on the clock?",
    timeMode: "read",
    displayedHour: 6,
    displayedMinute: 15,
    correctAnswer: "6:15"
},
{
    type: "time",
    class: "Nestlings Navigators",
    subject: "Mathematics",
    term: "Term 3",
    part: "End Term",
    question: "What time is shown on the clock?",
    timeMode: "read",
    displayedHour: 6,
    displayedMinute: 30,
    correctAnswer: "6:30"
},
{
    type: "time",
    class: "Nestlings Navigators",
    subject: "Mathematics",
    term: "Term 3",
    part: "End Term",
    question: "What time is shown on the clock?",
    timeMode: "read",
    displayedHour: 6,
    displayedMinute: 45,
    correctAnswer: "6:45"
},
{
    type: "time",
    class: "Nestlings Navigators",
    subject: "Mathematics",
    term: "Term 3",
    part: "End Term",
    question: "What time is shown on the clock?",
    timeMode: "read",
    displayedHour: 7,
    displayedMinute: 00,
    correctAnswer: "7:00"
},
{
    type: "time",
    class: "Nestlings Navigators",
    subject: "Mathematics",
    term: "Term 3",
    part: "End Term",
    question: "What time is shown on the clock?",
    timeMode: "read",
    displayedHour: 7,
    displayedMinute: 15,
    correctAnswer: "7:15"
},
{
    type: "time",
    class: "Nestlings Navigators",
    subject: "Mathematics",
    term: "Term 3",
    part: "End Term",
    question: "What time is shown on the clock?",
    timeMode: "read",
    displayedHour: 7,
    displayedMinute: 30,
    correctAnswer: "7:30"
},
{
    type: "time",
    class: "Nestlings Navigators",
    subject: "Mathematics",
    term: "Term 3",
    part: "End Term",
    question: "What time is shown on the clock?",
    timeMode: "read",
    displayedHour: 7,
    displayedMinute: 45,
    correctAnswer: "7:45"
},
{
    type: "time",
    class: "Nestlings Navigators",
    subject: "Mathematics",
    term: "Term 3",
    part: "End Term",
    question: "What time is shown on the clock?",
    timeMode: "read",
    displayedHour: 8,
    displayedMinute: 00,
    correctAnswer: "8:00"
},
{
    type: "time",
    class: "Nestlings Navigators",
    subject: "Mathematics",
    term: "Term 3",
    part: "End Term",
    question: "What time is shown on the clock?",
    timeMode: "read",
    displayedHour: 8,
    displayedMinute: 15,
    correctAnswer: "8:15"
},
{
    type: "time",
    class: "Nestlings Navigators",
    subject: "Mathematics",
    term: "Term 3",
    part: "End Term",
    question: "What time is shown on the clock?",
    timeMode: "read",
    displayedHour: 8,
    displayedMinute: 30,
    correctAnswer: "8:30"
},
{
    type: "time",
    class: "Nestlings Navigators",
    subject: "Mathematics",
    term: "Term 3",
    part: "End Term",
    question: "What time is shown on the clock?",
    timeMode: "read",
    displayedHour: 8,
    displayedMinute: 45,
    correctAnswer: "8:45"
},
{
    type: "time",
    class: "Nestlings Navigators",
    subject: "Mathematics",
    term: "Term 3",
    part: "End Term",
    question: "What time is shown on the clock?",
    timeMode: "read",
    displayedHour: 9,
    displayedMinute: 00,
    correctAnswer: "9:00"
},
{
    type: "time",
    class: "Nestlings Navigators",
    subject: "Mathematics",
    term: "Term 3",
    part: "End Term",
    question: "What time is shown on the clock?",
    timeMode: "read",
    displayedHour: 9,
    displayedMinute: 15,
    correctAnswer: "9:15"
},
{
    type: "time",
    class: "Nestlings Navigators",
    subject: "Mathematics",
    term: "Term 3",
    part: "End Term",
    question: "What time is shown on the clock?",
    timeMode: "read",
    displayedHour: 9,
    displayedMinute: 30,
    correctAnswer: "9:30"
},
{
    type: "time",
    class: "Nestlings Navigators",
    subject: "Mathematics",
    term: "Term 3",
    part: "End Term",
    question: "What time is shown on the clock?",
    timeMode: "read",
    displayedHour: 9,
    displayedMinute: 45,
    correctAnswer: "9:45"
},
{
    type: "time",
    class: "Nestlings Navigators",
    subject: "Mathematics",
    term: "Term 3",
    part: "End Term",
    question: "What time is shown on the clock?",
    timeMode: "read",
    displayedHour: 10,
    displayedMinute: 00,
    correctAnswer: "10:00"
},
{
    type: "time",
    class: "Nestlings Navigators",
    subject: "Mathematics",
    term: "Term 3",
    part: "End Term",
    question: "What time is shown on the clock?",
    timeMode: "read",
    displayedHour: 10,
    displayedMinute: 15,
    correctAnswer: "10:15"
},
{
    type: "time",
    class: "Nestlings Navigators",
    subject: "Mathematics",
    term: "Term 3",
    part: "End Term",
    question: "What time is shown on the clock?",
    timeMode: "read",
    displayedHour: 10,
    displayedMinute: 30,
    correctAnswer: "10:30"
},
{
    type: "time",
    class: "Nestlings Navigators",
    subject: "Mathematics",
    term: "Term 3",
    part: "End Term",
    question: "What time is shown on the clock?",
    timeMode: "read",
    displayedHour: 10,
    displayedMinute: 45,
    correctAnswer: "10:45"
},
{
    type: "time",
    class: "Nestlings Navigators",
    subject: "Mathematics",
    term: "Term 3",
    part: "End Term",
    question: "What time is shown on the clock?",
    timeMode: "read",
    displayedHour: 11,
    displayedMinute: 00,
    correctAnswer: "11:00"
},
{
    type: "time",
    class: "Nestlings Navigators",
    subject: "Mathematics",
    term: "Term 3",
    part: "End Term",
    question: "What time is shown on the clock?",
    timeMode: "read",
    displayedHour: 11,
    displayedMinute: 15,
    correctAnswer: "11:15"
},
{
    type: "time",
    class: "Nestlings Navigators",
    subject: "Mathematics",
    term: "Term 3",
    part: "End Term",
    question: "What time is shown on the clock?",
    timeMode: "read",
    displayedHour: 11,
    displayedMinute: 30,
    correctAnswer: "11:30"
},
{
    type: "time",
    class: "Nestlings Navigators",
    subject: "Mathematics",
    term: "Term 3",
    part: "End Term",
    question: "What time is shown on the clock?",
    timeMode: "read",
    displayedHour: 11,
    displayedMinute: 45,
    correctAnswer: "11:45"
},
{
    type: "time",
    class: "Nestlings Navigators",
    subject: "Mathematics",
    term: "Term 3",
    part: "End Term",
    question: "What time is shown on the clock?",
    timeMode: "read",
    displayedHour: 12,
    displayedMinute: 00,
    correctAnswer: "12:00"
},
{
    type: "time",
    class: "Nestlings Navigators",
    subject: "Mathematics",
    term: "Term 3",
    part: "End Term",
    question: "What time is shown on the clock?",
    timeMode: "read",
    displayedHour: 12,
    displayedMinute: 15,
    correctAnswer: "12:15"
},
{
    type: "time",
    class: "Nestlings Navigators",
    subject: "Mathematics",
    term: "Term 3",
    part: "End Term",
    question: "What time is shown on the clock?",
    timeMode: "read",
    displayedHour: 12,
    displayedMinute: 30,
    correctAnswer: "12:30"
},
{
    type: "time",
    class: "Nestlings Navigators",
    subject: "Mathematics",
    term: "Term 3",
    part: "End Term",
    question: "What time is shown on the clock?",
    timeMode: "read",
    displayedHour: 12,
    displayedMinute: 45,
    correctAnswer: "12:45"
},
];